PYTHON = python3

MAIN_SCRIPT = main.py

.PHONY: all run

all:
	@echo "Setting up the project..."
	# run python3 main.py -> due to change later with additional files.
# 'run' target for running the main Python script
run:
	$(PYTHON) $(MAIN_SCRIPT)