PYTHON = python3

MAIN_SCRIPT = main.py

.PHONY: all run

all:
	@echo "Setting up the project..."
	# RUN python3 main.py
	# make sure that the following libraries are installed on your machine:
	# import matplotlib.pyplot as plt
	# import numpy as np
	# import random
	# import textwrap
	# import matplotlib.patches as patches
# 'run' target for running the main Python script
run:
	$(PYTHON) $(MAIN_SCRIPT)